export const texts = {
  turkish: {
    languageButton: "SWITCH TO ENGLISH",
    darkTheme: "KARANLIK TEMA",
    lightTheme: "AYDINLIK TEMA",
    hireMe: "Bana ulaş",
    hero1: "Ben bir Frontend Geliştiriciyim",
    hero2:
      "... ve sağlam ve ölçeklenebilir ön uç ürünlerini harika kullanıcı deneyimleriyle şekillendirmeyi seven biriyim.",
    skills: "Yetenekler",
    profile: "Profil",
    basicinfo: "Temel Bilgiler",
    birthdate: "Doğum Tarihi",
    location: "Konum",
    education: "Eğitim",
    preferredrole: "Tercih Edilen Rol",
    aboutme: "Hakkımda",
    projects: "Projeler",
    viewsite: "Siteyi Görüntüle",
    sendmessage: "Bana bir mesaj gönder!",
    messagedesc:
      "Sorunuz veya teklifiniz mi var, yoksa sadece merhaba mı demek istiyorsunuz? Cesur olun.",
  },
  english: {
    languageButton: "TÜRKÇE'YE GEÇ",
    darkTheme: "DARK MODE",
    lightTheme: "LIGHT MODE",
    hireMe: "Hire me",
    hero1: "Creative thinker Minimalism lover",
    hero2:
      "Hi, I’m Almila. I’m a full-stack developer. If you are looking for a Developer who to craft solid and scalable frontend products with great user experiences. Let’s shake hands with me.",
    skills: "Skills",
    profile: "Profile",
    basicinfo: "Basic Information",
    birthdate: "Birth Date",
    location: "Location",
    education: "Education",
    preferredrole: "Preferred Role",
    aboutme: "About Me",
    projects: "Projects",
    viewsite: "View Site",
    sendmessage: "Send me a message!",
    messagedesc:
      "Got a question or proposal, or just want to say hello? Go ahead.",
  },
};
